FROM golang:1.16.2-alpine3.13 as development

ENV ROOT=/go/src/app
WORKDIR ${ROOT}

RUN apk update && apk add git
RUN go mod init app
RUN go get -u github.com/gin-gonic/gin
RUN go get -u github.com/cosmtrek/air 
RUN go build -o /go/bin/air github.com/cosmtrek/air
RUN chmod +x /go/bin/air

CMD air